### ISSUE TITLE
make the home page RESPONSIVE on mobile devices

### ISSUE THREAD

**Issue by Sahad-09** [Sahad-09/portfolio-Nextjs#2]
### path: src/app/page.tsx
![Screenshot (27)](https://github.com/Sahad-09/portfolio-Nextjs/assets/91364349/585d31aa-b48e-4788-888f-aac86f24eff2)
You can use tailwind or vanilla css (I'm using tailwind)
Just make the landing page responsive
**Goodluck, Happy coding** 💻❣

**Comment by NewtonFernandis** [comment]
@Sahad-09 I will work on this could you please assign this to me?

**Comment by Sahad-09** [comment]
@NewtonFernandis Yeah, you can start
